# Generated by Django 5.2.7 on 2025-10-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='item',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
